[package]
name = "rust_decimal"
version = "0.1.2"
authors = ["Paul Mason <paul@form1.co.nz>"]
description = "A Decimal Implementation written in pure Rust suitable for financial calculations."
license = "MIT"

[dependencies]
num = "0.1"
byteorder = "1.0"
serde = "0.9"
serde_json = "0.9"
lazy_static = "0.2"
postgres = { version = "0.14", optional = true }